# Generated by Django 3.2.5 on 2021-08-04 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=60)),
                ('course_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_title', models.CharField(max_length=100)),
                ('workshop_description', models.TextField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('workshop_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('founders', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=80)),
                ('business_reg_number', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('funding_stage', models.CharField(max_length=100)),
                ('date_started', models.DateTimeField(auto_now=True)),
                ('total_funds_needed', models.IntegerField(default=1)),
                ('full_project_details', models.TextField(max_length=1000)),
                ('campaign_pitch', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
