# Generated by Django 3.2.5 on 2021-08-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=100)),
                ('business_reg_number', models.CharField(max_length=100)),
                ('campaign_info', models.TextField(max_length=1000)),
            ],
        ),
    ]
