# Generated by Django 3.2.5 on 2021-08-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='user',
        ),
    ]
