# Generated by Django 3.2.5 on 2021-08-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='date_started',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_funds_left',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_funds_needed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_funds_raised',
            field=models.IntegerField(default=1),
        ),
    ]
